export {NavBar} from './NavBar'
export {Hero} from './Hero'
export {Main} from './Main'
export {Services} from './Services'
export {Reviews} from './Reviews'
export {Footer} from './Footer'
export {Contact} from './Contact'
